version: "2"

checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    enabled: false
  argument-count:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 6

plugins:
  sonar-python:
    enabled: true
    config:
      test_patterns:
        - "pygmt/**/tests/*.py"
    checks:
      python:S3776:
        enabled: false
      python:S107:
        enabled: false
      python:S1542:
        enabled: false

exclude_paths:
- "doc/**/*"
- "pygmt/tests/baseline/*"
- "pygmt/tests/data/*"
