# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changes related to docs.
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && \
          git diff --quiet origin/main -- \
              doc/ \
              examples \
              pygmt/**/*.py \
              ':!pygmt/tests' \
              README.md \
              ci/requirements/docs.yml \
              .readthedocs.yaml;
        then
          exit 183;
        fi
    pre_build:
      # Generate api stub files before building
      - make -C doc api

# Build documentation in the doc/ directory with Sphinx
sphinx:
   configuration: doc/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally declare the Python requirements required to build your docs
conda:
  environment: ci/requirements/docs.yml
python:
   install:
   - method: pip
     path: .
