codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: auto  # increase overall coverage on each pull request
        threshold: 0.25%  # Allow the coverage to drop by X%
        if_not_found: success
        if_ci_failed: failure
    patch:
      default:
        target: 90%  # >=90% of new changes should be tested
        if_not_found: success
        if_ci_failed: failure

comment: off

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"

cli:
  plugins:
    pycoverage:
      report_type: "json"
  runners:
    pytest:
      pytest_command: ["/home/runner/micromamba/envs/pygmt/bin/python", "-m", "pytest"]
      collect_tests_options:
        - "--ignore=doc/conf.py"
        - "--ignore-glob=examples/**/*.py"
