name: Bug report
description: Report a problem/bug to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: "Description of the problem"
      description: |
        Please be as detailed as you can when describing an issue.
        The more information we have, the easier it will be for us to track this down.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Full code that generated the error"
      description: "Provide an example code snippet that reproduces the bug."
      placeholder: "PASTE CODE HERE"
      render: python
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Full error message"
      description: "What was the error message you got?"
      placeholder: "PASTE ERROR MESSAGE HERE"
      render: python-traceback
    validations:
      required: false
  - type: textarea
    attributes:
      label: "System information"
      description: "Please paste the output of `python -c \"import pygmt; pygmt.show_versions()\"`"
      placeholder: "PASTE THE OUTPUT HERE"
      render: bash
    validations:
      required: true
